name: Create pull request to repository

on:
  workflow_call:
    inputs:
      target_repo:
        description: "Name of the repo the reference setup is cloned to"
        required: true
        type: string
      script_params:
        description: "Parameters to use in the script"
        type: string
        required: true
      team_short_name:
        description: "The project name used to create the data-ingestor repo"
        required: true
        type: string

env:
  TEAM_SHORT_NAME: ${{ inputs.team_short_name }}
  SCRIPT_PARAMS: ${{ inputs.script_params }}
  TARGET_REPO: ${{ inputs.target_repo }}

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f
        id: octo-sts
        with:
          scope: kartverket/${{ env.TARGET_REPO }}
          identity: dask-modules

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_wrapper: false

      - name: Set vars
        id: set-output
        run: |
          PRODUCT_NAME="$(echo ${{ secrets.GCP_SERVICE_ACCOUNT }} | sed 's/-deploy.*//')"
          DEFAULT_WORKLOAD_IDENTITY="projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/$PRODUCT_NAME-deploy-pool/providers/github-provider"
          OVERRIDE="$WORKLOAD_IDENTITY_PROVIDER_OVERRIDE"
          PROVIDER="${OVERRIDE:-$DEFAULT_WORKLOAD_IDENTITY}"
          echo "WORKLOAD_IDENTITY_PROVIDER=$PROVIDER" >> "$GITHUB_OUTPUT"

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ steps.set-output.outputs.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          export_environment_variables: true
          create_credentials_file: true

      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: "current-repo"

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: kartverket/${{ env.TARGET_REPO }}
          ref: main
          token: ${{ steps.octo-sts.outputs.token }}
          path: "target-repo"

      - name: Modify files
        working-directory: current-repo
        run: |
          python scripts/data_ingestor_update.py --payload '${{ env.SCRIPT_PARAMS }}'

      - name: Format Terraform Files
        working-directory: target-repo
        run: terraform fmt -recursive

      - name: Commit and Push to target repository
        working-directory: target-repo
        run: |
          HASH="$(date +%s | sha256sum | head -c 4)"
          BRANCH_NAME="dask-onboarding-ci-${{ env.TEAM_SHORT_NAME }}-${HASH}"
          echo "BRANCH_NAME=$BRANCH_NAME" >> "$GITHUB_ENV"

          git config --global user.name "DASK CI"
          git config --global user.email "noreply@kartverket.no"
          git checkout -b "$BRANCH_NAME"
          git add .
          git commit -m "Update files from DASK CI workflow"
          git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        id: create_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.octo-sts.outputs.token }}
          script: |

            const response = await github.rest.pulls.create({
              owner: 'kartverket',
              repo: ${{ env.TARGET_REPO }},
              title: 'Add new team from DASK CI workflow',
              head: process.env.BRANCH_NAME,
              base: 'main',
              draft: true
            });

            console.log('Pull Request created: ', response.data.html_url);
            core.setOutput('pullRequestUrl', response.data.html_url);
