name: Create pull request to repository

on:
  workflow_dispatch:
    inputs:
      payload:
        description: "Parameters to use in the script"
        type: string
        required: true

  workflow_call:
    inputs:
      payload:
        description: "Parameters to use in the script"
        type: string
        required: true

env:
  RESOURCE_NAME: ${{ fromJson(inputs.script_params).resource_name }}
  TARGET_REPO: ${{ fromJson(inputs.script_params).target_repo }}

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f
        id: octo-sts
        with:
          scope: kartverket/${{ env.TARGET_REPO }}
          identity: dask-modules

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_wrapper: false

      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: dask-modules

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: kartverket/${{ env.TARGET_REPO }}
          ref: main
          token: ${{ steps.octo-sts.outputs.token }}
          path: target-repo

      - name: Modify files
        working-directory: target-repo
        run: |
          python ../dask-modules/scripts/data_ingestor_update.py --payload '${{ inputs.payload }}'

      - name: Format Terraform Files
        working-directory: target-repo
        run: terraform fmt -recursive

      - name: Commit and Push to target repository
        working-directory: target-repo
        run: |
          HASH="$(date +%s | sha256sum | head -c 4)"
          BRANCH_NAME="dask-onboarding-ci-${{ env.RESOURCE_NAME }}-${HASH}"
          echo "BRANCH_NAME=$BRANCH_NAME" >> "$GITHUB_ENV"

          git config --global user.name "DASK CI"
          git config --global user.email "noreply@kartverket.no"
          git checkout -b "$BRANCH_NAME"
          git add .
          git commit -m "Update files from DASK CI workflow"
          git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        id: create_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.octo-sts.outputs.token }}
          script: |

            const response = await github.rest.pulls.create({
              owner: 'kartverket',
              repo: '${{ env.TARGET_REPO }}',
              title: 'Konfigurer repo for ${{ env.RESOURCE_NAME }}',
              head: process.env.BRANCH_NAME,
              base: 'main'
            });

            console.log('Pull Request created: ', response.data.html_url);
            core.setOutput('pullRequestUrl', response.data.html_url);

  publish-teams-output-to-pubsub:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs:
      - create_pull_request
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: projects/149356773285/locations/global/workloadIdentityPools/dataplattform-deploy-pool/providers/github-provider
          service_account: dataplattform-deploy@dataplattform-prod-9b1d.iam.gserviceaccount.com
          project_id: dataplattform-prod-9b1d

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          version: ">= 363.0.0"

      - name: Publish message to Pub/Sub topic
        env:
          PUBSUB_TOPIC: projects/onboarding-bf12/topics/onboarding-prod
          TEAM_SHORT_NAME: ${{ fromJson(inputs.script_params).team_short_name }}
        run: |
          json_message='{"commit_hash": "${{ github.sha }}", "event_type": "ingestor-configured", "payload": { "team_short_name": "${{ env.TEAM_SHORT_NAME }}" }}'

          gcloud pubsub topics publish ${{ env.PUBSUB_TOPIC }} --message="$json_message"
